### ISSUE TITLE
missing 1 required positional argument

### ISSUE THREAD

**Issue by theroddimus** [acidvegas/booster#4]
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python39\booster.py", line 148, in <module>
    Booster.run()
TypeError: run() missing 1 required positional argument: 'self'
>>>

**Comment by theroddimus** [comment]
code wont run due to this traceback

**Comment by acidvegas** [comment]
My response is a little late, this project was mostly abandoned years ago....I just hate having open issues on my work so [here you go](https://github.com/acidvegas/booster/commit/8238d1c3031fddd2dd6d41ad71c15af640cc3bcf). Issue fixed.
